name: Build Windows Installer

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'       # не указываем cache, чтобы не требовался lock-файл

      - name: Install deps
        run: npm install --no-audit --no-fund

      - name: Build UI (Vite)
        run: npm run build:ui

      - name: Install native deps for Electron (better-sqlite3)
        env:
          npm_config_build_from_source: true
          npm_config_runtime: electron
          npm_config_target: 31.7.7
          npm_config_disturl: https://electronjs.org/headers
          npm_config_target_arch: x64
        run: npm run install-app-deps

      - name: Build Windows installer (NSIS)
        run: npm run build:win

      - name: Upload installer artifact
        uses: actions/upload-artifact@v4
        with:
          name: Offline-POS-Installer
          path: dist/*.exe
