name: Build Windows Installer

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build UI
        run: npm run build:ui

      - name: Install native deps for Electron
        run: npm run install-app-deps

      - name: Build Windows installer
        run: npm run build:win

      - name: Upload installer artifact
        uses: actions/upload-artifact@v4
        with:
          name: Offline-POS-Installer
          path: |
            dist/Offline POS Setup *.exe
            dist/win-unpacked/**
