name: Build Windows Installer

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          # cache не включаем, т.к. у нас нет lock-файла

      - name: Install dependencies
        run: npm ci || npm install

      - name: Ensure dev deps (Vite/React/Tailwind/PostCSS/esbuild)
        run: npm install -D tailwindcss@3 postcss@8 autoprefixer@10 @vitejs/plugin-react@4 esbuild@0.23

      - name: Build UI (Vite)
        run: npm run build:ui

      - name: Build Electron main (esbuild)
        run: npm run build:electron

      - name: Install native deps for Electron (better-sqlite3)
        run: npx electron-builder install-app-deps

      - name: Build Windows installer (NSIS)
        run: npm run build:win

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: OfflinePOS-win
          path: dist/*.exe
